version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  allow:
  - dependency-name: "*adevinta*"
  - dependency-name: "*gowse*"
  ignore:
  - dependency-name: github.com/lib/pq
    versions:
    - 1.3.0
