dist: trusty
language: go
go:
  - 1.13.3
env:
  global:
    - CGO_ENABLED=0
services:
  - redis-server
gobuild_args: -a -tags netgo -ldflags '-w'
go_import_path: github.com/adevinta/vulcan-stream
before_script: 
  - curl -sfL https://raw.githubusercontent.com/adevinta/vulcan-local/dev/script/get | sh
script:
  - go test -v $(go list ./... | grep -v /vendor/)
  - vulcan-local -t . -s all -l debug
  - _script/test
after_success:
  - bash -c 'source <(curl -s https://raw.githubusercontent.com/adevinta/vulcan-cicd/master/docker.sh)'
