dist: trusty
language: go
go:
  - 1.12.7
env:
  global:
    - CGO_ENABLED=0
    - GO111MODULE=on
services:
  - postgresql
before_script:
  - psql -c 'create database stream;' -U postgres
gobuild_args: -a -tags netgo -ldflags '-w'
go_import_path: github.com/adevinta/vulcan-stream
script:
  - go test -v $(go list ./... | grep -v /vendor/)
  - _script/test
  - |
      wget https://raw.githubusercontent.com/adevinta/Publish-Docker-Github-Action/master/entrypoint.sh -O docker.sh
      chmod +x docker.sh
      export INPUT_USERNAME=$DOCKER_USERNAME
      export INPUT_PASSWORD=$DOCKER_PASSWORD
      export INPUT_NAME=$TRAVIS_REPO_SLUG
deploy:
  provider: script
  script: ./docker.sh
  on:
    tags: true
    all_branches: true