dist: trusty
language: go
go:
  - 1.13.3
env:
  global:
    - CGO_ENABLED=0
services:
  - postgresql
before_script:
  - psql -c 'create database stream;' -U postgres
gobuild_args: -a -tags netgo -ldflags '-w'
go_import_path: github.com/adevinta/vulcan-stream
script:
  - go test -v $(go list ./... | grep -v /vendor/)
  - _script/test
after_success:
  - bash -c 'source <(curl -s https://raw.githubusercontent.com/adevinta/Publish-Docker-Github-Action/travis/entrypoint.sh)'
