dist: bionic
language: go
go:
  - 1.18.2
env:
  global:
    - CGO_ENABLED=0
services:
  - redis-server
gobuild_args: -a -tags netgo -ldflags '-w'
go_import_path: github.com/adevinta/vulcan-stream
script:
  - go test -v $(go list ./... | grep -v /vendor/)
  - go install ./...
  - _script/test
after_success:
  - bash -c 'source <(curl -s https://raw.githubusercontent.com/adevinta/vulcan-cicd/master/docker.sh)'
