[Logger]
LogFile = ""
LogLevel = "$LOG_LEVEL"

[API]
Port = $PORT

[Storage]
Addr = "$REDIS_ADDR"
Usr = "$REDIS_USR"
Pwd = "$REDIS_PWD"
DB = $REDIS_DB
TTL = $REDIS_TTL

[Sender]
HTTPStream = "stream"
PingInterval = 10

[Metrics]
enabled = $DOGSTATSD_ENABLED
