#! /bin/bash

set -e

function clean() {
    redis-cli flushall
}

function test_ws_client() {
    vulcan-stream-test-client "${TRAVIS_BUILD_DIR}"/_resources/config/test.toml
    if [ $? -eq 0 ]; then
        printf "\033[1;32m[SUCCESS] STREAM INTEGRATION TEST COMPLETED\033[0m\n"
    else
        printf "\033[1;31m[FAIL] STREAM INTEGRATION TEST FAILED\033[0m\n"
        exit 1
    fi
}

clean

# Start vulcan-stream
vulcan-stream "${TRAVIS_BUILD_DIR}"/_resources/config/test.toml &
test_ws_client
exit 0
