# VulcanStream local configuration file template
[Logger]
LogFile = ""
LogLevel = "DEBUG"

[API]
Port = 8080

[Storage]
Host = "127.0.0.1"
Port = 6379
Usr = ""
Pwd = ""
DB = 0
TTL = 0

[Sender]
PingInterval = 5
