# VulcanStream local configuration file template
[Logger]
LogFile = ""
LogLevel = "DEBUG"

[API]
Port = 8080

[Storage]
Addr = "127.0.0.1:6379"
Usr = ""
Pwd = ""
DB = 0
TTL = 0

[Sender]
PingInterval = 5
